project_name: driverkit
builds:
  - id: driverkit
    goos:
    - linux
    goarch:
    - amd64
    main: ./main.go
    binary: driverkit

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - driverkit
    replacements:
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test'